package answer.fun.funquizes;

public class Array {
    final int [] images1 = {
            R.drawable.onelevel_zero,
            R.drawable.onelevel_one,
            R.drawable.onelevel_two,
            R.drawable.onelevel_three,
            R.drawable.onelevel_four,
            R.drawable.onelevel_five,
            R.drawable.onelevel_six,
            R.drawable.onelevel_seven,
            R.drawable.onelevel_eight,
            R.drawable.onelevel_nine,
    };


    final int[] texts1 ={
            R.string.lvl1text0,
            R.string.lvl1text1,
            R.string.lvl1text2,
            R.string.lvl1text3,
            R.string.lvl1text4,
            R.string.lvl1text5,
            R.string.lvl1text6,
            R.string.lvl1text7,
            R.string.lvl1text8,
            R.string.lvl1text9,

    };

    final int[] even = {
            1,0,1,0,1,0,1,0,1,0,
    };

    final int [] images2 = {
            R.drawable.homak,
            R.drawable.zaec,
            R.drawable.kangaroo,
            R.drawable.tulen,
            R.drawable.volk,
            R.drawable.medved,
            R.drawable.lev,
            R.drawable.begemot,
            R.drawable.verblud,
            R.drawable.dgiraf,
            R.drawable.slon,
            R.drawable.kit,
    };


    final int[] texts2 ={
            R.string.lvl2text0,
            R.string.lvl2text1,
            R.string.lvl2text2,
            R.string.lvl2text3,
            R.string.lvl2text4,
            R.string.lvl2text5,
            R.string.lvl2text6,
            R.string.lvl2text7,
            R.string.lvl2text8,
            R.string.lvl2text9,
            R.string.lvl2text9,
            R.string.lvl2text10,
            R.string.lvl2text11,
    };

    final int [] images3 = {
            R.drawable.pluton,
            R.drawable.mercurii,
            R.drawable.mars,
            R.drawable.venera,
            R.drawable.earth,
            R.drawable.neptun,
            R.drawable.uran,
            R.drawable.saturn,
            R.drawable.upiter,






    };


    final int[] texts3 ={
            R.string.lvl3text0,
            R.string.lvl3text1,
            R.string.lvl3text2,
            R.string.lvl3text3,
            R.string.lvl3text4,
            R.string.lvl3text5,
            R.string.lvl3text6,
            R.string.lvl3text7,
            R.string.lvl3text8,




    };
final int[] texts111 ={
        R.string.ten,
        R.string.eleven,
        R.string.twelve,
        R.string.therteen,
        R.string.fourteen,
        R.string.fifteen,
        R.string.sixteen,
        R.string.seventeen,
        R.string.eighteen,
        R.string.nineteen,
        R.string.twenty,
        R.string.twentyone,
        R.string.twentytwo,
        R.string.twentythree,
        R.string.twentyfour,
        R.string.twentyfive,
        R.string.twentysix,
        R.string.twentyseven,
        R.string.twentyeight,
        R.string.twentynine,
        R.string.thirty,
        R.string.thirtyone,
        R.string.thirtytwo,
        R.string.thirtythree,
        R.string.thirtyfour,
        R.string.thirtyfive,
        R.string.thirtysix,
        R.string.thirtyseven,
        R.string.thirtyeight,
        R.string.thirtynine,
        R.string.fourty,
        R.string.fourtyone,
        R.string.fourtytwo,
        R.string.fourtythree,
        R.string.fourtyfour,
        R.string.fourtyfive,
        R.string.fourtysix,
        R.string.fourtyseven,
        R.string.fourtyeight,
        R.string.fourtynine,
        R.string.fifty,
        R.string.fiftyone,
        R.string.fiftytwo,
        R.string.fiftythree,
        R.string.fiftyfour,
        R.string.fiftyfive,
        R.string.fiftysix,
        R.string.fiftyseven,
        R.string.fiftyeight,
        R.string.fiftynine,
        R.string.sixty,
        R.string.sixtyone,
        R.string.sixtytwo,
        R.string.sixtythree,
        R.string.sixtyfour,
        R.string.sixtyfive,
        R.string.sixtysix,
        R.string.sixtyseven,
        R.string.sixtyeight,
        R.string.sixtynine,
        R.string.seventy,
        R.string.seventyone,
        R.string.seventytwo,
        R.string.seventythree,
        R.string.seventyfour,
        R.string.seventyfive,
        R.string.seventysix,
        R.string.seventyseven,
        R.string.seventyeight,
        R.string.seventynine,
        R.string.eighty,
        R.string.eightyone,
        R.string.eightytwo,
        R.string.eightythree,
        R.string.eightyfour,
        R.string.eightyfive,
        R.string.eightysix,
        R.string.eightyseven,
        R.string.eightyeight,
        R.string.eightynine,
        R.string.ninty,
        R.string.nintyone,
        R.string.nintytwo,
        R.string.nintythree,
        R.string.nintyfour,
        R.string.nintyfive,
        R.string.nintysix,
        R.string.nintyseven,
        R.string.nintyeight,
        R.string.nintynine,
        R.string.onehun,
};

final int[] numbers111 = {
       10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,
        40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,
        70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,
};

final int[] images111 = {
        R.drawable.ten,
        R.drawable.eleven,
        R.drawable.twelve,
        R.drawable.therteen,
        R.drawable.fourteen,
        R.drawable.fifteen,
        R.drawable.sixteen,
        R.drawable.seventeen,
        R.drawable.eighteen,
        R.drawable.nineteen,
        R.drawable.twenty,
        R.drawable.twentyone,
        R.drawable.twentytwo,
        R.drawable.twentythree,
        R.drawable.twentyfour,
        R.drawable.twentyfive,
        R.drawable.twentysix,
        R.drawable.twentyseven,
        R.drawable.twentyeight,
        R.drawable.twentynine,
        R.drawable.thirty,
        R.drawable.thirtyone,
        R.drawable.thirtytwo,
        R.drawable.thirtythree,
        R.drawable.thirtyfour,
        R.drawable.thirtyfive,
        R.drawable.thirtysix,
        R.drawable.thirtyseven,
        R.drawable.thirtyeight,
        R.drawable.thirtynine,
        R.drawable.fourty,
        R.drawable.fourtyone,
        R.drawable.fourtytwo,
        R.drawable.fourtythree,
        R.drawable.fourtyfour,
        R.drawable.fourtyfive,
        R.drawable.fourtysix,
        R.drawable.fourtyseven,
        R.drawable.fourtyeight,
        R.drawable.fourtynine,
        R.drawable.fifty,
        R.drawable.fiftyone,
        R.drawable.fiftytwo,
        R.drawable.fiftythree,
        R.drawable.fiftyfour,
        R.drawable.fiftyfive,
        R.drawable.fiftysix,
        R.drawable.fiftyseven,
        R.drawable.fiftyeight,
        R.drawable.fiftynine,
        R.drawable.sixty,
        R.drawable.sixtyone,
        R.drawable.sixtytwo,
        R.drawable.sixtythree,
        R.drawable.sixtyfour,
        R.drawable.sixtyfive,
        R.drawable.sixtysix,
        R.drawable.sixtyseven,
        R.drawable.sixtyeight,
        R.drawable.sixtynine,
        R.drawable.seventy,
        R.drawable.seventyone,
        R.drawable.seventytwo,
        R.drawable.seventythree,
        R.drawable.seventyfour,
        R.drawable.seventyfive,
        R.drawable.seventysix,
        R.drawable.seventyseven,
        R.drawable.seventyeight,
        R.drawable.seventynine,
        R.drawable.eighty,
        R.drawable.eightyone,
        R.drawable.eightytwo,
        R.drawable.eightythree,
        R.drawable.eightyfour,
        R.drawable.eightyfive,
        R.drawable.eightysix,
        R.drawable.eightyseven,
        R.drawable.eightyeight,
        R.drawable.eightynine,
        R.drawable.ninty,
        R.drawable.nintyone,
        R.drawable.nintytwo,
        R.drawable.nintythree,
        R.drawable.nintyfour,
        R.drawable.nintyfive,
        R.drawable.nintysix,
        R.drawable.nintyseven,
        R.drawable.nintyeight,
        R.drawable.nintynine,
        R.drawable.onehun,
};

}
